// This file would be generated by the FlutterFire CLI
// For this example, we're creating a placeholder

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: 'A#',
    appId: '#',
      messagingSenderId: '#',
    projectId: '#"',
    storageBucket: '#',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'A#',
    appId: '#',
      messagingSenderId: '#',
    projectId: '#"',
    storageBucket: '#',
  );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: 'A#',
    appId: '#',
    messagingSenderId: '#',
    projectId: '#"',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'YOUR-IOS-BUNDLE-ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
   apiKey: 'A#',
    appId: '#',
    messagingSenderId: '#,
    projectId: '#',
   storageBucket: '#',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'YOUR-IOS-BUNDLE-ID',
  );
}

